AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a security group for the Linux machine.
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: VPC-Peter
  VPCID:
    Description: The ID of the VPC for the security group
    Type: AWS::EC2::VPC::Id
    Default: !ImportValue
      Fn::Sub: "${EnvironmentName}-VPCID"
Resources:
  LinuxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access to Linux machine
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Linux Security Group
Outputs:
  LinuxSecurityGroupID:
    Description: Export Linux Security Group ID
    Value: !Ref LinuxSecurityGroup
    Export:
      Name: !Sub "${EnvironmentName}-LinuxSecurityGroupID"
