Parameters:
  ApplicationName:
    Description: The application name
    Type: String
    Default: PeterTawfikSG
  VPCId:
    Description: VPC to create the security group into
    Type: String
  
Resources:
  Ec2SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Security group for ${ApplicationName}
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/25"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          Description: SSH for Engineering department
        - CidrIp: "109.255.230.190/32"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          Description: SSH for my public IP
      VpcId: !Ref VPCId

  DBSSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Security group for ${ApplicationName}
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/25"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          Description: SSH for Engineering department
      VpcId: !Ref VPCId

Outputs:
  SSHGroupId:
    Value: !Ref Ec2SSHSecurityGroup
    Description: Id for the SSH Security Group